module.exports = {
  printWidth: 150,
  tabWidth: 2,
  useTabs: false,
  semi: false,
  singleQuote: true,
  trailingComma: 'es5',
  arrowParens: 'avoid',
  bracketSpacing: true,
  bracketSameLine: false,
  embeddedLanguageFormatting: 'off',
  proseWrap: 'preserve',
  htmlWhitespaceSensitivity: 'css',
  requirePragma: false,
  insertPragma: false,
  jsxSingleQuote: false,
  plugins: ['prettier-plugin-tailwindcss', 'prettier-plugin-organize-imports'],
  quoteProps: 'as-needed',
}
